myflask/posts/views.py
# -*- coding: utf-8 -*-
"""Posts section"""
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
    session,
)
from flask_login import current_user, login_required

from ..extensions import login_manager
from ..utils import flash_errors
from ..public.forms import LoginForm
from ..user.models import User
from .forms import PostForm
from .models import Post

blueprint = Blueprint("posts", __name__, url_prefix="/posts", static_folder="../static")


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.get_by_id(int(user_id))


@blueprint.route("/", methods=["GET", "POST"])
def index():
    current_app.logger.info("Hello from the posts page!")
    form = PostForm()
    if request.method == "POST":
        if form.validate_on_submit():
            user = User.get_by_id(current_user.get_id())
            Post.create(
                body=form.body.data,
                user=user,
            )
            flash("Blog created", "success")
            return redirect(url_for(".index"))
        else:
            flash_errors(form)
    form = LoginForm()
    posts = Post.query.all()
    return render_template("posts/index.html", form=form, posts=posts)


@blueprint.route("/add")
@login_required
def add():
    current_app.logger.info("Add page")
    form = PostForm()
    return render_template("posts/add.html", form=form)


@blueprint.route("/<int:post_id>", methods=["GET", "POST"])
@login_required
def edit(post_id):
    current_app.logger.info("Hello from the posts edit page!")
    form = PostForm()
    post = Post.get_by_id(post_id)
    if request.method == "POST":
        if form.validate_on_submit():
            post.update(
                body=form.body.data,
            )
            flash("Blog updated", "success")
            return redirect(url_for(".edit", post_id=post.id))
        else:
            flash_errors(form)
    return render_template("posts/edit.html", form=form, post=post)

myflask/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    """List members."""
    return render_template("users/members.html")

myflask/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

myflask/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Edward</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:edward@me.com">Contact</a></li>
    </ul>
  </small>
</footer>

myflask/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{{ config.APP_TITLE }} :: {% block page_title %}

    My Flask

    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {{ stylesheet_tag('main_css') | safe }}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>

<main role="main">
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div><!-- end .alert -->
            {% endfor %}
          </div><!-- end col-md -->
        </div><!-- end row -->
{% endif %}
{% endwith %}

{% block content %}{% endblock %}
</main>


{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{{ javascript_tag('main_js') | safe }}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

myflask/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
     My Flask
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.endpoint == 'public.home' %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('public.home') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item {% if request.endpoint == 'public.about' %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('public.about') }}">About</a>
      </li>
      <li class="nav-item {% if 'posts.' in request.endpoint %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('posts.index') }}">Blogs</a>
      </li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
    <form class="form-inline" id="loginForm" method="POST" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
        class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">
        <a class="nav-link navbar-text" href="{{ url_for('public.register') }}">Create account</a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>